spring:
  datasource:
    url: jdbc:h2:file:~/db/projectaccount2
    username: incubadora
    password: 123123
  jpa:
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop